#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="reg")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertconnection(connection instance);
  partial void Updateconnection(connection instance);
  partial void Deleteconnection(connection instance);
  partial void Insertmobile(mobile instance);
  partial void Updatemobile(mobile instance);
  partial void Deletemobile(mobile instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["regConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<connection> connections
	{
		get
		{
			return this.GetTable<connection>();
		}
	}
	
	public System.Data.Linq.Table<mobile> mobiles
	{
		get
		{
			return this.GetTable<mobile>();
		}
	}
	
	public System.Data.Linq.Table<register> registers
	{
		get
		{
			return this.GetTable<register>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.connection")]
public partial class connection : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _name;
	
	private string _billing_address;
	
	private string _tariff_plan;
	
	private string _date;
	
	private string _status;
	
	private string _pincode;
	
	private string _no_of;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onbilling_addressChanging(string value);
    partial void Onbilling_addressChanged();
    partial void Ontariff_planChanging(string value);
    partial void Ontariff_planChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnpincodeChanging(string value);
    partial void OnpincodeChanged();
    partial void Onno_ofChanging(string value);
    partial void Onno_ofChanged();
    #endregion
	
	public connection()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billing_address", DbType="NVarChar(MAX)")]
	public string billing_address
	{
		get
		{
			return this._billing_address;
		}
		set
		{
			if ((this._billing_address != value))
			{
				this.Onbilling_addressChanging(value);
				this.SendPropertyChanging();
				this._billing_address = value;
				this.SendPropertyChanged("billing_address");
				this.Onbilling_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tariff_plan", DbType="NChar(10)")]
	public string tariff_plan
	{
		get
		{
			return this._tariff_plan;
		}
		set
		{
			if ((this._tariff_plan != value))
			{
				this.Ontariff_planChanging(value);
				this.SendPropertyChanging();
				this._tariff_plan = value;
				this.SendPropertyChanged("tariff_plan");
				this.Ontariff_planChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NChar(10)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pincode", DbType="NChar(10)")]
	public string pincode
	{
		get
		{
			return this._pincode;
		}
		set
		{
			if ((this._pincode != value))
			{
				this.OnpincodeChanging(value);
				this.SendPropertyChanging();
				this._pincode = value;
				this.SendPropertyChanged("pincode");
				this.OnpincodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_of", DbType="NChar(10)")]
	public string no_of
	{
		get
		{
			return this._no_of;
		}
		set
		{
			if ((this._no_of != value))
			{
				this.Onno_ofChanging(value);
				this.SendPropertyChanging();
				this._no_of = value;
				this.SendPropertyChanged("no_of");
				this.Onno_ofChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mobile")]
public partial class mobile : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _c_id;
	
	private string _conn_type;
	
	private string _service_req;
	
	private System.Nullable<int> _mig_no;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onc_idChanging(string value);
    partial void Onc_idChanged();
    partial void Onconn_typeChanging(string value);
    partial void Onconn_typeChanged();
    partial void Onservice_reqChanging(string value);
    partial void Onservice_reqChanged();
    partial void Onmig_noChanging(System.Nullable<int> value);
    partial void Onmig_noChanged();
    #endregion
	
	public mobile()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string c_id
	{
		get
		{
			return this._c_id;
		}
		set
		{
			if ((this._c_id != value))
			{
				this.Onc_idChanging(value);
				this.SendPropertyChanging();
				this._c_id = value;
				this.SendPropertyChanged("c_id");
				this.Onc_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conn_type", DbType="NChar(10)")]
	public string conn_type
	{
		get
		{
			return this._conn_type;
		}
		set
		{
			if ((this._conn_type != value))
			{
				this.Onconn_typeChanging(value);
				this.SendPropertyChanging();
				this._conn_type = value;
				this.SendPropertyChanged("conn_type");
				this.Onconn_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_req", DbType="NChar(10)")]
	public string service_req
	{
		get
		{
			return this._service_req;
		}
		set
		{
			if ((this._service_req != value))
			{
				this.Onservice_reqChanging(value);
				this.SendPropertyChanging();
				this._service_req = value;
				this.SendPropertyChanged("service_req");
				this.Onservice_reqChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mig_no", DbType="Int")]
	public System.Nullable<int> mig_no
	{
		get
		{
			return this._mig_no;
		}
		set
		{
			if ((this._mig_no != value))
			{
				this.Onmig_noChanging(value);
				this.SendPropertyChanging();
				this._mig_no = value;
				this.SendPropertyChanged("mig_no");
				this.Onmig_noChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.register")]
public partial class register
{
	
	private string _fnm;
	
	private string _lnm;
	
	private string _g;
	
	private string _fname;
	
	private string _mname;
	
	private string _dob;
	
	private string _address;
	
	private System.Nullable<int> _contact;
	
	private string _state;
	
	private string _city;
	
	private string _ocp;
	
	private string _pin;
	
	private string _email;
	
	private string _pwd;
	
	private string _cpwd;
	
	private string _nty;
	
	private string _mst;
	
	private string _img;
	
	public register()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fnm", DbType="NVarChar(50)")]
	public string fnm
	{
		get
		{
			return this._fnm;
		}
		set
		{
			if ((this._fnm != value))
			{
				this._fnm = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lnm", DbType="NVarChar(50)")]
	public string lnm
	{
		get
		{
			return this._lnm;
		}
		set
		{
			if ((this._lnm != value))
			{
				this._lnm = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_g", DbType="NVarChar(50)")]
	public string g
	{
		get
		{
			return this._g;
		}
		set
		{
			if ((this._g != value))
			{
				this._g = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="NVarChar(50)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this._fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mname", DbType="NVarChar(50)")]
	public string mname
	{
		get
		{
			return this._mname;
		}
		set
		{
			if ((this._mname != value))
			{
				this._mname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="NVarChar(50)")]
	public string dob
	{
		get
		{
			return this._dob;
		}
		set
		{
			if ((this._dob != value))
			{
				this._dob = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this._address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact", DbType="Int")]
	public System.Nullable<int> contact
	{
		get
		{
			return this._contact;
		}
		set
		{
			if ((this._contact != value))
			{
				this._contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(MAX)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this._state = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(MAX)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this._city = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ocp", DbType="NVarChar(50)")]
	public string ocp
	{
		get
		{
			return this._ocp;
		}
		set
		{
			if ((this._ocp != value))
			{
				this._ocp = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin", DbType="NVarChar(MAX)")]
	public string pin
	{
		get
		{
			return this._pin;
		}
		set
		{
			if ((this._pin != value))
			{
				this._pin = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50)")]
	public string pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this._pwd = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpwd", DbType="NVarChar(50)")]
	public string cpwd
	{
		get
		{
			return this._cpwd;
		}
		set
		{
			if ((this._cpwd != value))
			{
				this._cpwd = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nty", DbType="NVarChar(50)")]
	public string nty
	{
		get
		{
			return this._nty;
		}
		set
		{
			if ((this._nty != value))
			{
				this._nty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mst", DbType="NVarChar(50)")]
	public string mst
	{
		get
		{
			return this._mst;
		}
		set
		{
			if ((this._mst != value))
			{
				this._mst = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
	public string img
	{
		get
		{
			return this._img;
		}
		set
		{
			if ((this._img != value))
			{
				this._img = value;
			}
		}
	}
}
#pragma warning restore 1591
